### PR TITLE
Directory structure

### PR DESCRIPTION
**Pull request by ujjwal95**
New directory structure for the project.

### CODE REVIEW

**Comment by ujjwal95** [comment]
I was thinking of a different directory structure, one which would showcase each module of the project.

|
|--- data (can be a part of .gitignore)
|--- scrapers  ---|
                              |---./scrapers/ *.py .....
|--- preprocessing ---|
                                      |--- ./preprocessing /input_data (can be a part of .gitignore)
                                      |--- ./preprocessing /*.py .....
|--- modelling ---|
                              |--- ./modelling /input_data (can be a part of .gitignore)
                              |--- ./modelling /*.py .....
|--- evaluation ---|
                               |--- ./evaluation /models (can be a part of .gitignore)
                               |--- ./evaluation /*.py .....
|--- eda ---|
                     |---./eda/ *.py .....
|--- topic_modelling ---|
                                         |--- ./topic_modelling/*.py .....

Let me know what you think of it.

**Review by ameyakarnad — APPROVED** [review]
Looks like atleast the initial part is similar (For "HTML Extractions") , we can work out the small changes in teh structure later

**Review by aastha99 — APPROVED** [review]

**Review by Nirali22 — APPROVED** [review]

**Comment by ujjwal95** [comment]
Can we discuss on the final directory structure before going ahead with this?

**Comment by ameyakarnad** [comment]
As I mentioned, if the first part of the Directory structure (scrapers) is fine, let's move ahead and make changes for the rest of the structure later as we progress. If we wait for a discussion and then make a decision, the PRs may keep piling up and we may lose track. I am fine with either 

Let's not name it as "scrapers" and make it too obvious :)  You can make any necessary changes inside t the data collection folder.

Let me know if this does not make sense. If so, we can revert this and do everything after discussion or something

**Comment by ujjwal95** [comment]
Deciding on a uniform directory structure which makes sense and is easy to follow and code is an important part of a project. Changing the directory frequently is not something that is desirable in a project as the complete code needs to be changed frequently in portions that should be fixed. 

We do not have any PRs piling up, and for deciding a uniform structure, we can all hop on a call today and then make our decision.

**Pull request merged**
