### PR TITLE
Add NW Florida Daily Extractor

### PR DESCRIPTION
**Pull request by ujjwal95**
I added a new py file with sample ipynb file which does the following:

1. Checks URL, whether it belongs to NW Florida Daily Blog, or the base website, and processes them differently.
2. Checks whether the page exists or not, a few articles did not exist.
3. Finds heading, date, author, article body, and any hyperlinks in the article body.
4. Processes date to standard format for future processing.

### CODE REVIEW

**Review by ameyakarnad — APPROVED** [review]
Are we adding Jupyter notebooks as well? I thought that adding a .py file was the standard operating procedure (especially for data preprocessing steps). 

I am hoping that we could keep the things standard and add a jupyter notebook only if we were demonstrating something using google colab or something.

**Comment by ujjwal95** [comment]
I order to ensure that my code can be run by someone else, I added the jupyter notebook to show how to run the code. This ensures that if someone else needs to write some code in order to run my files, all that they need to do is refer to my jupyter notebook.

**Comment by ujjwal95** [comment]
If we are talking about standard, then most of the code we are writing isn't standard anyway, so we can relax on the code being 'standard'.

**Comment by ameyakarnad** [comment]
I understand that but was wondering if I was really necessary for us to maintain jupyter notebooks for code which would definitely not be rerun (especially creation part)

Anyway, this will not adversely impact the code, so we can go ahead with what is present.

**Review by saranggupta94 — APPROVED** [review]

**Review by aastha99 — APPROVED** [review]

**Review by Nirali22 — APPROVED** [review]

**Pull request merged**
