### PR TITLE
Washington Observer Report + Changes

### PR DESCRIPTION
**Pull request by ameyakarnad**
The tasks in this PR are

- Moved NYT to a specific directory (2 files)
- Added Washington Observer Report in HTML Extraction (1 file)
- Changed Readme (1 file)

### CODE REVIEW

**Comment by ujjwal95** [comment]
iterrows is slower, try to use apply, that is faster.
For now, it is fine.

**Review by ujjwal95 — APPROVED** [review]

**Review by Nirali22 — COMMENTED** [review]
So, for the content of the article: If you are not able to access article body, you are accessing all the content listed in the 'p' tag, right?
Also, apply function will be faster than iterrows. You can try that.

**Review by saranggupta94 — APPROVED** [review]
Looks good to me!

**Comment by ameyakarnad** [comment]
Hi @Nirali22 


> So, for the content of the article: If you are not able to access the article body, you are accessing all the content listed in the 'p' tag, right?

Nope, That's not what I was doing. I was doing something stupid that was not required and your comment made me realize that :D

Also, I found that all the articles had an 'articleBody' so did not put a fool-proof system for conditions where it did not exist. Now changed the code to reflect that.  Thanks! 

> Also, apply function will be faster than iterrows. You can try that.

I know that, but I put the iterrows deliberately. I thought that if you run the code on huge amount of links, we would have 2 problems,
1. apply would execute the "get_article" function first on all the link, which may lead to huge amount of HTML data stored in the RAM.
2. The same reason may cause the site to throw a DOS. so time between requests may help our cause

Let me know if these reasons seem valid, If not, I can make the change

**Review by aastha99 — APPROVED** [review]

**Comment by ujjwal95** [comment]
To solve this, you can request the article in a separate parent function, which then calls all the functions and then use apply on that. 

But it doesn't matter for now, this seems good.

**Comment by ameyakarnad** [comment]
@ujjwal95   I am not sure if you got me right.  "apply" would bring down the execution time, which is something I wanted to avoid to ensure DOS doesn't happen

**Comment by ameyakarnad** [comment]
As there are no other comments, I am moving ahead with the merge

**Pull request merged**
